# Site settings
title: Philipp Gniewosz
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://brandshaide.github.io

# User settings
username: Philipp Gniewosz
user_description: I\'m a Senior Software Engineer and fanatic about FP & Haskell; 
user_title: Senior Software Engineer
email: philipp.gniewosz@posteo.de
twitter_username: @PGniewosz
github_username:  brandshaide
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
